<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Fantasy.Net\Fantasy.Net\Fantasy.Net.csproj" />
      <ProjectReference Include="..\Entity\Entity.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Benchmark\" />
      <Folder Include="Outer\Game\" />
      <Folder Include="Outer\NormalMessage\" />
      <Folder Include="Outer\NormalMessage\Gate\" />
      <Folder Include="Outer\RouteMessage\" />
      <Folder Include="Outer\SubScene\" />
    </ItemGroup>

</Project>
