syntax = "proto3";
package Fantasy.Network.Message;
// 协议分为:
// ProtoBuf:可以在Outer和Inner文件里使用。
// MemoryPack:可以在Outer和Inner文件里使用。
// Bson:仅支持在Inner文件里使用。
// 使用方式:
// 在message协议上方添加// Protocol+空格+协议名字
// 例如:// Protocol ProtoBuf 或 // Protocol MemoryPack

// -----------------登录, 选择角色-----------------

message Send_RegisterAccount // IRequest ,Rcv_RegisterAccount
{
  string user_name = 1 ;
  string pass_word = 2 ;
}

message Rcv_RegisterAccount // IResponse
{
  string user_name = 1;
  string pass_word = 2;
}



message Send_GetLoginToken // IRequest ,Rcv_GetLoginToken
{
  string account_name = 1; // 账号
  string pass_word = 2; // 密码
}

message Rcv_GetLoginToken // IResponse
{
  string token = 1; // 登陆令牌
  string login_address = 2; // 登录地址
  int64 account_id = 3; // 账号id
  uint32 scene_config_id = 4;
}

message Send_LoginGate // IRequest ,Rcv_LoginGate
{
  int64 account_id = 1;
  string token = 2;
  uint32 scene_config_id = 3;
}

message Rcv_LoginGate // IResponse
{
  int64 account_id = 1; // 账号id
  int64 level = 2;
  int64 gold = 3;
  int64 diamond = 4;
  repeated RoleData role_datas = 5;
}


message RoleData
{
  int64 uid = 1; // 角色唯一id
  string role_name = 2; // 名字
  int32 level = 3; // 等级
  int32 role_id = 4; // 用于区分职业 
  int64 account_id = 5; // 所属账号id 
}

message Send_CreateRole // IRequest ,Rcv_CreateRole
{
  int32  role_id = 1;
  int64 account_id = 2;
  string role_name = 3;
}

message Rcv_CreateRole  // IResponse
{
  RoleData role_data = 1;
}

message Send_SelectRole // IRequest ,Rcv_SelectRole
{
  int64 role_uid = 1;
  int64 account_id = 2;
}

message Rcv_SelectRole  // IResponse
{
  RoleData role_data = 1;
}


// 请求: 进入地图
message Send_EnterMap // IRequest ,Rcv_EnterMap
{
  int64 player_id = 1; // account_id
  int32 cur_map = 2; // 当前所处地图: 如果是未登录,那么是 -1
  int32 map_type = 3; // 要进入的地图id
}

// 响应: 进入地图
message Rcv_EnterMap  // IResponse
{
  int64 player_id = 1; // account_id
  int32 map_type = 2; // 要进入的地图id
  CSVector3 role_init_pos = 3; // 初始化位置
}

// -----------------队伍相关----------------

// 请求:创建队伍
message Send_CreateTeam // IRequest ,Rcv_CreateTeam
{
  int64 account_id = 1; // 创建队伍的玩家
  int32 map_type = 2; //是打哪个副本的队伍
}
// 响应:创建队伍
message Rcv_CreateTeam  // IResponse
{
  int32 team_id = 1; // 队伍id
  RoleData role_data = 2; // 创建队伍的角色
}

// 请求:加入队伍
message Send_JoinTeam // IRequest ,Rcv_JoinTeam
{
  int64 account_id = 1;// 请求加入队伍的用户
  int32 map_type = 2 ; // 哪个副本
  int32 team_id = 3;// 请求加入哪个队伍
}

// 响应:加入队伍
message Rcv_JoinTeam // IResponse
{
  int32 team_id = 1;// 请求加入哪个队伍
  repeated RoleData team_role_list = 2;// 队伍成员
}

message Msg_TeamStateChanged // IMessage 
{
  int32 team_state = 1; // 1.玩家加入 2.玩家离开 3.队伍解散
  RoleData role_data = 2;// 哪个玩家导致的状态变更
}



// -----------------大厅状态同步协议-----------------

message Send_StateSync // IRequest ,Rcv_StateSync
{
  int64 state_pack_id = 1; // 状态数据包id
  StateSyncData role_sync_data = 2; // 同步数据
}

message Rcv_StateSync  // IResponse
{
  int64 state_pack_id = 1; // 状态数据包id
  StateSyncData role_sync_data = 2; // 同步数据
}


// ----------------副本相关协议-----------------

// 进入地下城的通知
message Msg_EnterDungeon // IMessage 
{
  int32 team_id = 1; // 队伍ID
  int32 dungeonCfgID = 2; // 进入哪个地下城
  repeated  RoleData teamMembers = 3 ; // 队伍成员列表
}

// 客户端加载地下城通知
message Msg_LoadDungeonProgress // IMessage 
{
  int32 team_id = 1;
  int64 account_id = 2;
  float progress = 3 ; // 地下城加载进度 (0~1)
}


// 开始地下城战斗
message Msg_StartDungeonBattle // IMessage 
{
  repeated RoleData battle_role_datas = 1;
  RoleData team_leader = 2;
}




// 状态同步的数据包
message  StateSyncData
{
  int64 player_id = 1; // 玩家id
  int32 map_type = 2; // 所在地图
  CSVector3 position = 3; // 玩家位置
  CSVector3 input_dir = 4; // 玩家输入方向
  int32 state = 5 ; // 玩家状态: 待机,行走,奔跑
  int32 role_id = 6 ; // 玩家角色职业类型: 鬼剑士, 神枪手
  int32 player_map_status = 7; // 1: 处于地图中 2:离开地图   对应枚举:PlayerMapStatus
}


// 其他玩家状态数据通知
message Msg_OtherPlayerStateSync // IMessage
{
  StateSyncData role_data = 1;
}

message  CSVector3
{
  float x = 1;
  float y = 2;
  float z = 3;
}

message  CSFixIntVector3
{
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
}


// ----------------战斗帧同步-----------------

// 帧操作事件 客户端打包帧操作数据给服务器
message Msg_C2S_FrameOpEvent // IMessage 
{
  int64 battle_id = 1; // 战斗id
  repeated FrameOperateData frame_operate_datas = 2; // 帧操作事件列表
}

// 帧操作事件广播: 服务端广播客户端的数据给多个客户端
message Msg_S2C_FrameOpEvent // IMessage 
{
  int64 battle_id = 1; // 战斗id
  repeated FrameOperateData frame_operate_datas = 2; // 帧操作事件列表
  int64 logic_frame_id = 3;
}

// 操作帧数据
message FrameOperateData
{
  int32 operate_type = 1; // 0:无操作 1:方向输入 2:释放技能 // EBattlePlayerOpType
  CSFixIntVector3 input_dir = 2; // 输入方向
  int32 skillId = 3; // 技能id
  int32 skillType = 4; // 技能类型
  CSFixIntVector3 skillPos = 5; // 技能位置: 引导位置等...
  int64  account_id = 6; // 用户
  int64 frame_op_context_object_id = 7; // 帧操作上下文对象id
}
